name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni olish
        uses: actions/checkout@v4

      - name: Papkalar tuzilishini ko'rsatish
        run: find . -maxdepth 4 -not -path '*/.git*'
